travis:
  secure:
    BINSTAR_TOKEN: MeuXuQQKBMtg3jzTA4DiXLmDNbYmVTfVeszCNmP5oLcrcBRRpqUNdtLziq//UKdeJ75CcdTUAWSw36dJSgC5HepfPCEa1ZWCLQYKAZK89vgxhoa7PO1/mijmJ+wpYM5JWRd80JREej5P4GTzoAQ+JgHDX/nYct/hf6rB5Ge6AEgEu9mqYJiL0DEVos9cJHYCVqyCp8/LlhFCdXH7x0TKXEBBQ5OnX6rTEQ0SY6S1W0sISIEP2C3zLZiH05dbF11UZEvXhuf7GNBSv4YIMyvdGfJYaLja8dcwtmyVY1ydRASeIRLYBRdzDq7PtFBd5c5bObTha59z+LYFwQ4MZY4InGAtKTjoyg0Bkcat78N1A3dm2YRqaN4YzC11npDOXUEMh1Sed74arLUk1CXpSXtzjnFRfFvFXlZlwpGZs574bPF8poVDUnCWRCgGVsSXEBpv7gXOuvDu0m2LqHyXhKScChUHNGS2eywnSP2n8ftfxW1AD65jvwu6NCPQFJbRRWs4cmQdn8phfeiDwbb9M7P/GPSeSLnjp8Vhfaow/ztkqmsGiDBBXK+kGdu4PGKwvHl1OLlnSF1Fcp4dIG5/DCMQT+7LXguAZFflVu6zt/T+tEaZfctjF6FKGmUw/CipiIpew1p0ux5qaTZcBETfFoI367774soUPy90E3HAfJHNbYo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
