travis:
  secure:
    BINSTAR_TOKEN: vOQ1EYj2LnT6s834nbxQqNlQE4CE3rAx7ONSOGWw3VNXEUwZ87x5S4fNV2XFAPU8sFNukD0k+WSyeKzlojkDD18lIQYMH1Ebhx1vSdRzlPVzoNASWw8PxtDjBaSW1IbNyJGH+HmAS+EQ0itjPyAEwM8zfbwDFgpSNRNxkO9wR+t1dgMZcbD8AXgUpsptmN3efYs7Yk7hK6Z3oeW9ImPlsOh77QLDGL8XyPYYywbbKqbZQfOubyX1pdPBSr0GET1SzV+ge8SmlYUn6GNXRy+92Mci0T2p4Ol/Jbrz+T6CrrNm6RfPqp4oehhr4PaH2fsvH6bjq9iVY1703SgdIqacjnqbDQEvMd3+cmujZYBS8MFfZsExgOkuuGE8fuiuH+gMNH54Ks4CMW2dAIK70UUImdqtlj2VQ8yMaEy0GyiaYeQ/3CnsawYAMPdfc1977krsF4JZQBgPmZForNuYfTuYiSnAENhTal/cr4jyfqkXiRfmwn5asx4OfHYa5iuwyTqVpObIGPL9QSaXPYaE/B3oWUX+KBqeFS4IFAd/SDKftp920Wp4HcYtLQ0LhVcHufUI/q8HdM4CDkf6T69x+k09Kz8ekKo/GcM7ZuQgIHvGMG34StqFV7DUYlMe8YqzfUtRKMBN1JFsTNV6l9IAEMdJZHxRBeu9EikDjP8nQsh3T2g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
